#!/usr/bin/perl -w
# Copyright (C) 2016 Konstantin Tokavev <annulen@yandex.ru>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

use FindBin;
use lib $FindBin::Bin;
use webkitdirs;

my $scriptsDir = relativeScriptsDir();
system("perl", "$scriptsDir/update-webkit-libs-jhbuild", "--qt", @ARGV) == 0 or die $!;

my $jhbuildRootDir = baseProductDir() . "/DependenciesQT/Root";

if (-f "$jhbuildRootDir/lib/qt_common.debug") {
    print "Skipping optimization of Qt debug info - remove $jhbuildRootDir/lib/qt_common.debug if Qt was reinstalled\n";
} else {
    print "Optimizing Qt debug info\n";
    system("dwz -m $jhbuildRootDir/lib/qt_common.debug -M qt_common.debug \$(find $jhbuildRootDir/lib -name 'libQt5*.so*' -type f)") == 0 or die $!;
}

my $mesaBuildDir = baseProductDir() . "/DependenciesQT/Build/Mesa/lib/gallium";
print "Copying llvmpipe libGL.so to $jhbuildRootDir/lib/Mesa/gallium\n";
mkdir "$jhbuildRootDir/lib/Mesa";
system("cp -ax $mesaBuildDir $jhbuildRootDir/lib/Mesa") == 0 or die $!;
